version: "3.9"
services:
  server-1:
    image: grpc-server
    build:
      context: ./app
      dockerfile: Dockerfile
    command:
      - ./server
      - -rsp_delay
      - "0"
      - -variance
      - "2"
    networks:
      - envoymesh
  # server-2:
  #   image: grpc-server
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   command:
  #     - ./server
  #     - -rsp_delay
  #     - "20"
  #   networks:
  #     - envoymesh
     
  client:
    image: grpc-client
    build:
      context: ./app
      dockerfile: Dockerfile
    command:
      - ./client
      - -server_addr
      - envoy:50051
      - -num_threads
      - "10"
      - -reqs_per_thread
      - "10000"
      - -burst_size
      - "80"
      - -burst_interval
      - "100"
    depends_on:
      - envoy
      - server-1
#      - server-2
    networks:
      - envoymesh
  envoy:
    image: envoyproxy/envoy:v1.20.0
    ports:
      - "9000:9000"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoymesh

networks:
  envoymesh: {}
