version: "3.9"
services:
  server-1:
    image: grpc-server
    build:
      context: ./app
      dockerfile: Dockerfile.golang
    command:
      - ./server
      - -rsp_delay
      - "20"
      - -variance
      - "5"
    networks:
      - envoymesh
  client:
    image: obvionaoe/ghz
    command:
      - --insecure
      - --config=/ghz/client/config.yaml
      - --proto=/ghz/proto/hello-world.proto
      - --call=helloworld.Greeter.SayHello
      - envoy:50051
    volumes:
      - ./app/proto:/ghz/proto
      - ./app/client:/ghz/client
    depends_on:
      - envoy
      - server-1
#      - server-2
    networks:
      - envoymesh
  envoy:
    image: envoyproxy/envoy:v1.20.0
    ports:
      - "9000:9000"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoymesh

  prometheus:
    image: prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - envoymesh

  grafana:
    image: grafana/grafana:8.2.2-ubuntu
    ports:
      - "3000:3000"
    networks:
      - envoymesh

networks:
  envoymesh: {}
