version: "3.9"
services:
  server-1:
    image: grpc-server
    build:
      context: ./app
      dockerfile: Dockerfile.golang
    command:
      - -delay
      - "20"
      - -dprob
      - "0"
      - -cancel
      - -cprob
      - "10"
    ports:
      - "50051:50051"
    networks:
      - envoymesh
  client:
    image: obvionaoe/ghz
    command:
      - --config=/ghz/client/config.json
      - envoy:50051
    volumes:
      - ./app/client:/ghz/client
      - ./app/proto:/ghz/proto
    depends_on:
      - envoy
      - server-1
    networks:
      - envoymesh
  envoy:
    image: envoyproxy/envoy:v1.20.0
    ports:
      - "9000:9000"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoymesh

  prometheus:
    image: prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - envoymesh

  grafana:
    image: grafana/grafana:8.2.2-ubuntu
    ports:
      - "3000:3000"
    networks:
      - envoymesh

networks:
  envoymesh: {}
