version: "3.9"
services:
  server-1:
    image: grpc-server
    build:
      context: ./app
      dockerfile: Dockerfile
    command:
      - ./server
      - -rsp_delay
      - "100"
      - -variance
      - "0"
    networks:
      - envoymesh
  server-2:
    image: grpc-server
    build:
      context: ./app
      dockerfile: Dockerfile
    command:
      - ./server
      - -rsp_delay
      - "20"      
    networks:
      - envoymesh
     
  client:
    image: grpc-client
    build:
      context: ./app
      dockerfile: Dockerfile
    command:
      - ./client
      - -server_addr
      - envoy:50051
      - -num_threads
      - "2"
      - -reqs_per_thread
      - "1000000"
      - -burst_size
      - "10"
      - -burst_interval
      - "100"
    depends_on:
      - envoy
      - server-1
      - server-2
    networks:
      - envoymesh
  envoy:
    image: envoyproxy/envoy:v1.14.1
    ports:
      - "9000:9000"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoymesh

  prometheus:
    image: prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - envoymesh

  grafana:
    image: grafana/grafana:8.2.2-ubuntu
    ports:
      - "3000:3000"
    environment:
      - "DS_USER=admin"
      - "DS_PASS=pass"
    networks:
      - envoymesh

networks:
  envoymesh: {}
