version: "3.9"
services:
  server-1:
    image: grpc-server
    build:
      context: ./app
      dockerfile: ${DOCKERFILE}
    command:
      - -log
      - "DEBUG"
      - -delay
      - "20000"
      - -dprob
      - "0"
      - -cancel
      - -cprob
      - "0"
    ports:
      - "50051:50051"
      - "8000:8000"
    networks:
      - envoymesh
  client-1:
    image: obvionaoe/ghz
    command:
      - --config=/ghz/client/unary_req_unary_rsp.json
      - envoy:50051
    volumes:
      - ./app/client:/ghz/client
      - ./app/proto:/ghz/proto
    depends_on:
      - envoy
      - server-1
    networks:
      - envoymesh
  client-2:
    image: obvionaoe/ghz
    command:
      - --config=/ghz/client/unary_req_stream_rsp.json
      - envoy:50051
    volumes:
      - ./app/client:/ghz/client
      - ./app/proto:/ghz/proto
    depends_on:
      - envoy
      - server-1
    networks:
      - envoymesh
  client-3:
    image: obvionaoe/ghz
    command:
      - --config=/ghz/client/stream_req_unary_rsp.json
      - envoy:50051
    volumes:
      - ./app/client:/ghz/client
      - ./app/proto:/ghz/proto
    depends_on:
      - envoy
      - server-1
    networks:
      - envoymesh
  client-4:
    image: obvionaoe/ghz
    command:
      - --config=/ghz/client/stream_req_stream_rsp.json
      - envoy:50051
    volumes:
      - ./app/client:/ghz/client
      - ./app/proto:/ghz/proto
    depends_on:
      - envoy
      - server-1
    networks:
      - envoymesh      
  envoy:
    image: envoyproxy/envoy:v1.22.0
    ports:
      - "9000:9000"
      - "8081:8081"
    command:
      - --log-level
      - debug
      - --config-path
      - "/etc/envoy/envoy.yaml"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoymesh

  prometheus:
    image: prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - envoymesh

  grafana:
    image: grafana/grafana:8.2.2-ubuntu
    ports:
      - "3000:3000"
    networks:
      - envoymesh

networks:
  envoymesh: {}
