---
async: true
dial_timeout: 5

total: 30000    # Total requests
rps: 2000       # Requests per second

# Concurrency configuration
concurrency-schedule: step
concurrency-start: 20
concurrency-step: 20
concurrency-end: 200 # Max concurrency
concurrency-step-duration: "1s"


data:
  clientName: "{{ .WorkerID }}"
  seqNum: "{{ .RequestNumber }}"
metadata:
  clientID: "{{ .WorkerID }}"
