FROM python:3.7.12-alpine

RUN apk add --no-cache \
    g++ \
    musl-dev \
    libffi-dev \
    libstdc++ \
    && python -m pip install pip-tools

RUN mkdir -p /app/src
WORKDIR /app
COPY server/python/requirements.in .
RUN pip-compile requirements.in && pip install -r requirements.txt
RUN apk del \
    g++ \
    musl-dev \
    libffi-dev

COPY server/python/src /app/src/
COPY proto/python/ /app/src/

WORKDIR /app/src
ENTRYPOINT ["python3", "./main.py"]
